var layouts = {};
layouts["en"] = {
    name: "English",
    icon: "iVBORw0KGgoAAAANSUhEUgAAACAAAAAcCAYAAAAAwr0iAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAA2RpVFh0WE1MOmNvbS5hZG9iZS54bXAAAAAAADw/eHBhY2tldCBiZWdpbj0i77u/IiBpZD0iVzVNME1wQ2VoaUh6cmVTek5UY3prYzlkIj8+IDx4OnhtcG1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iIHg6eG1wdGs9IkFkb2JlIFhNUCBDb3JlIDUuMC1jMDYwIDYxLjEzNDc3NywgMjAxMC8wMi8xMi0xNzozMjowMCAgICAgICAgIj4gPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4gPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIgeG1sbnM6eG1wTU09Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9tbS8iIHhtbG5zOnN0UmVmPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvc1R5cGUvUmVzb3VyY2VSZWYjIiB4bWxuczp4bXA9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC8iIHhtcE1NOk9yaWdpbmFsRG9jdW1lbnRJRD0ieG1wLmRpZDpDRTUxMjNGN0Q5RDJFMDExQkI3QkRGOUNFMzAzQThBQSIgeG1wTU06RG9jdW1lbnRJRD0ieG1wLmRpZDozRUYwNDlGNzVGREQxMUUyQkM2MDk5QzBCRTQyNjExQiIgeG1wTU06SW5zdGFuY2VJRD0ieG1wLmlpZDozRUYwNDlGNjVGREQxMUUyQkM2MDk5QzBCRTQyNjExQiIgeG1wOkNyZWF0b3JUb29sPSJBZG9iZSBQaG90b3Nob3AgQ1M1IFdpbmRvd3MiPiA8eG1wTU06RGVyaXZlZEZyb20gc3RSZWY6aW5zdGFuY2VJRD0ieG1wLmlpZDo1OUVDNTc3RkQzNUZFMjExQjZCMkMzMkRFRjFGMDVEQSIgc3RSZWY6ZG9jdW1lbnRJRD0ieG1wLmRpZDpDRTUxMjNGN0Q5RDJFMDExQkI3QkRGOUNFMzAzQThBQSIvPiA8L3JkZjpEZXNjcmlwdGlvbj4gPC9yZGY6UkRGPiA8L3g6eG1wbWV0YT4gPD94cGFja2V0IGVuZD0iciI/PsYQet8AAAaxSURBVHjaxFcLUFRlFP7u7t1dWGARdRENfBSKg6/AxlIzswQfU2ZZlKbhA4kyo9LKml6m02jZIBXKI6exh4WTTQ970GBhNJUlI0abq5GEi6y4obC77Pvu37n/vbBo0yjTlGfmzP33/Pc/5/znfOecuwJjDJeSNLjEJE6ZMkWbnJxsMJvNWoPBAI3mv/UpHA7D7/fD4XBILS0tftHpdJp2FKw+EzvjWgiCgNOnXaipsaKjwy37d/5xHrT8/Glor3gbgkbgUhZmGLByMcrLa+mXRKw971wI/Qb2w3WThiLu18PwWI8h+vaxuGZ1QX+xqakp3vXWblkNjFdfhcTEOMyfnwmLpQU22xk1S8I5DsikS0qkpSpXcZSUFH+eA4o8ZYQZo816sCO/8N2EnAUQk8yQbYsej8cQWrEMQvMxtG/fAdPcbESlpyEjYxj0eh2qqy1wd3khMB2YIJErWsybNx6+hiMUIK1inCJguikbDQ0naT9E/sqRC8JoikPW9aOQ6mqBc28tdCNTYZqTBU2MEY4/3ZBt8xg/UlqHZ9dmIzXmMNpLymC8dir6LZiHMWOGwEwRqXzvAKzWFvX2SloCrXYIWmXNJIk/W1vPcsMypU24AjlThyCm+iM4fmtC/IL5iJsxle9ZLCdRVFQVqQJ7Uxt2vPk9PsYwmJbcjeCBA7Bv2Az/b8eRaI7DqgduRFbWBHi9fmLFAPP4wLxehX1eLpP3vP4QZs6diLx0EUJpCdydbiSuLeTGg1IYu3f/hIqK/bDbOyMOhEIC3E4fPni3Fi9+5UBo5f2I0YuwP7UenXu/pFQLhIsMrFqVha6ugIIGjxeSyuEuxQF5L3/5dMz6sx6OV1+DLiMTg59cA/3wZLS1ubBh/cfYs+cHuN0BsqmWoeKAHy6XhxQEcei7ehRSiAqW3oQrk1PQXloO3+EGDMi7BxMnDkdl5UrFATdViU6tkpCSgl0lt6H9hS1oa7bBfN+9iJ05DSHCxzdfWVFW9jXpd9JbemIPAgFPbwcYnE4/gSLIg+JyteP5jZ/hsXVzkV00Gd7GRkguFzTxJmiiDKoDHgi6bgwo1wl1OhE1+wb0p5uL5gFcVlVlwYubvlCrQsurRJKC8PmUapLrKI0ag1UUxT41oWOTZhEItT0gHPVjVZ+aUYhyQI1vNL/C0XHTIcZEQ/Ap+aWO1FPbfN2bZDnJBB2VpYx49bd17HWRM/9E6rvMoIMUCEVSQAVOaPZTBQUv+hYsEPi78os9SxFgarTF7hxKTsppHxz4N8QoejDF9gIhoVPb5YPQXRsXJC2BUa+ulRSFfX61DV+EA4S3sMAiDqT/UU9tV98nEP4cPZTjgCskx8d7m/sEwoCcwuhoxYHBSWsQCGpIeO4Nyl9fjGW5UxQjwRB8R6y8TKPHp9Nl6V21CiBFzoW7PNQZ/fCfaEZUSgp2fnoU+Xlvn6NXr9cSs0gnDIaCfGQyJrMHOl0YW7bchoV3TeIvuaprYRmZCfviPBgS+0dAx8LydXqmHldIg0bq7IT9mc2wDBuD2Y5DeKVkIaLjDXSki9uQbcm9oFcrVpbhsBcjRyZj//7HUVg4E1E0q9peKMLv2XMwZHIGmtcXQxzyXM83AGemPLkGTQH27TsC/eXDccVH72Dg2odw6rFHcUfVNtRU5mLM1WO5DRk3wWC4x+k0UcxlRuNytnBhGWs77WIy+ZtOsMab72IWXQLrfGkrK62oZcaEVWQpn+/XC4PYYUMy53ptEpfJewbDUlZcXM26qePDz1nDZaNZU+o4dvKDKrZ09W6ylU+FkCt7ncYjYDSKNB6XYNeufJp+seh4/xNYM6dB13gUpspKPHA8CQUrd8BztvOCAPPTNCws3ImcnO04dcqJ+FtmY/Shb8EmZODsHXeieHAzSrbnwmQ2RSJQU3OIUTtmAaeLHb9vDatDLDv94Br2xZ7v2aiM9eTpIuIVxPcQ51EPCrCDFIE6w2WcD1IEZJm8ByxRn4vYiBFr2d699XxP5tbiMnZQP5C13JrDvnzzEx4BPgtsNptVZ2uF7eEnoWm1IeG5p1F6IgZlJdWQ+KzvrvkAX9tsm/Dr0EwIerWR0jRM/6MOKSnret5RKMhLe/nyaXh83RzClA6+X6xoefgJeBqPY3rHCT4LJPsbu9D6UhGMqSPge3oD8nc2oO6bn1VFwjkfl3LrsNvtaHM7e01DCQkkc7vPqF9Eut5tB1u3vk/grMPGjbcSyAfBWF4E78vbgHcqJFn7IOJxxOb/+S+Bg7hBdkAe8HHq8/8kuXe7hEv91+wvAQYAsaE9RMg/tfAAAAAASUVORK5CYII=",
    sets: ["all"],
    all: ["`", "1", "2", "3", "4", "5", "6", "7", "8", "9", "0", "-", "=", "backspace", "EOL",
        "tab", "q", "w", "e", "r", "t", "y", "u", "i", "o", "p", "[", "]", "\\", "EOL",
        "{capslock}", "a", "s", "d", "f", "g", "h", "j", "k", "l", ";", "\'", "returnUS", "EOL",
        "[shiftUS]", "z", "x", "c", "v", "b", "n", "m", ",", ".", "/", "[rightshift]", "EOL",
        "selector", "[alt]", "space", "[alt]", "EOL"],
    all_alt: ["`", "¡","™","£","¢","∞","§","¶","•","ª","º","–","≠", "backspace", "EOL",
        "tab", "œ", "∑", "´", "®", "†", "¥", "¨", "ˆ", "ø", "π", "“", "‘", "«", "EOL",
        "{capslock}", "å", "ß", "∂", "ƒ", "©", "˙", "∆", "˚", "¬", "…", "æ", "returnUS", "EOL",
        "[shiftUS]", "Ω", "≈", "ç", "√", "∫", "˜", "µ", "≤", "≥", "÷", "[rightshift]" ,"EOL",
        "selector", "[alt]" , "space", "[alt]", "EOL"],
    all_shift: ["~", "!", "@", "#", "$", "%", "^", "&", "*", "(", ")", "_", "+", "backspace", "EOL",
        "tab", "Q", "W", "E", "R", "T", "Y", "U", "I", "O", "P", "{", "}", "|", "EOL",
        "{capslock}", "A", "S", "D", "F", "G", "H", "J", "K", "L", ":", "'", "returnUS", "EOL",
        "[shiftUS]", "Z", "X", "C", "V", "B", "N", "M", "<", ">", "?", "[rightshift]", "EOL",
        "selector", "[alt]", "space", "[alt]", "EOL"],
    all_capslock: ["~", "1", "2", "3", "4", "5", "6", "7", "8", "9", "0", "-", "=", "backspace", "EOL",
        "tab", "Q", "W", "E", "R", "T", "Y", "U", "I", "O", "P", "{", "}", "|", "EOL",
        "{capslock}", "A", "S", "D", "F", "G", "H", "J", "K", "L", ":", "'", "returnUS", "EOL",
        "[shiftUS]", "Z", "X", "C", "V", "B", "N", "M", "<", ">", "?", "[rightshift]", "EOL",
        "selector", "[alt]", "space", "[alt]", "EOL"],
    all_alt_shift: ["`","⁄","€","‹","›","ﬁ","ﬂ","‡","°","·","‚","—","±","backspace",
        "tab", "Œ","„","´","‰","ˇ","Á","¨","ˆ","Ø","∏","”","’","»","EOL",
        "{capslock}", "Å","Í","Î","Ï","˝","Ó","Ô","","Ò","Ú","Æ", "returnUS", "EOL",
        "[shiftUS]","¸","˛","Ç","◊","ı","˜","Â","¯","˘","¿","[rightshift]", "EOL",
        "selector", "[alt]", "space", "[alt]", "EOL"],
    all_alt_capslock: ["`", "¡","™","£","¢","∞","§","¶","•","ª","º","–","≠", "backspace", "EOL",
        "tab", "Œ","„","´","‰","ˇ","Á","¨","ˆ","Ø","∏","”","’","»","EOL",
        "{capslock}", "Å","Í","Î","Ï","˝","Ó","Ô","","Ò","Ú","Æ", "returnUS", "EOL",
        "[shiftUS]","¸","˛","Ç","◊","ı","˜","Â","¯","˘","¿","[rightshift]", "EOL",
        "selector", "[alt]", "space", "[alt]", "EOL"],
    all_shift_capslock: ["all_shift"],
    all_capslock_shift: ["all_shift"],
    all_shift_alt: ["all_alt_shift"],
    all_capslock_alt: ["all_alt_capslock"],
    all_alt_capslock_shift: ["all_alt_shift"],
    all_alt_shift_capslock: ["all_alt_shift"],
    all_shift_alt_capslock: ["all_alt_shift"],
    all_capslock_alt_shift: ["all_alt_shift"],
    all_capslock_shift_alt: ["all_alt_shift"],
    all_shift_capslock_alt: ["all_alt_shift"]
};

layouts["ru"] = {
    name: "Русский",
    icon: "iVBORw0KGgoAAAANSUhEUgAAACAAAAAcCAYAAAAAwr0iAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAA2RpVFh0WE1MOmNvbS5hZG9iZS54bXAAAAAAADw/eHBhY2tldCBiZWdpbj0i77u/IiBpZD0iVzVNME1wQ2VoaUh6cmVTek5UY3prYzlkIj8+IDx4OnhtcG1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iIHg6eG1wdGs9IkFkb2JlIFhNUCBDb3JlIDUuMC1jMDYwIDYxLjEzNDc3NywgMjAxMC8wMi8xMi0xNzozMjowMCAgICAgICAgIj4gPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4gPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIgeG1sbnM6eG1wTU09Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9tbS8iIHhtbG5zOnN0UmVmPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvc1R5cGUvUmVzb3VyY2VSZWYjIiB4bWxuczp4bXA9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC8iIHhtcE1NOk9yaWdpbmFsRG9jdW1lbnRJRD0ieG1wLmRpZDpDRTUxMjNGN0Q5RDJFMDExQkI3QkRGOUNFMzAzQThBQSIgeG1wTU06RG9jdW1lbnRJRD0ieG1wLmRpZDozRUYwNDlGMzVGREQxMUUyQkM2MDk5QzBCRTQyNjExQiIgeG1wTU06SW5zdGFuY2VJRD0ieG1wLmlpZDozRUYwNDlGMjVGREQxMUUyQkM2MDk5QzBCRTQyNjExQiIgeG1wOkNyZWF0b3JUb29sPSJBZG9iZSBQaG90b3Nob3AgQ1M1IFdpbmRvd3MiPiA8eG1wTU06RGVyaXZlZEZyb20gc3RSZWY6aW5zdGFuY2VJRD0ieG1wLmlpZDo1OUVDNTc3RkQzNUZFMjExQjZCMkMzMkRFRjFGMDVEQSIgc3RSZWY6ZG9jdW1lbnRJRD0ieG1wLmRpZDpDRTUxMjNGN0Q5RDJFMDExQkI3QkRGOUNFMzAzQThBQSIvPiA8L3JkZjpEZXNjcmlwdGlvbj4gPC9yZGY6UkRGPiA8L3g6eG1wbWV0YT4gPD94cGFja2V0IGVuZD0iciI/Pm2HIkMAAAGuSURBVHjaxFfNTgIxEJ7uAtVFTTxsTAwHPW98AXwujz6YJ30HH8ALB5O9qLhAdzutM7A/DVlQEmwnGZaWhu/r9PumIKy1EDIiCByD6XQaTyYTmaZpLKWEKPpfTsYYUEpBnuc4m80UZFl2aQMFY4skSW6KongLUf7xeHwbLRYLyWXxHYzJ2OsDR0TwSYKxGLN1QQgrNpjBbRi+D/DL/cMTXKdnsCzRC+jpKIaP+bIjUJEo5ssKVtWWEPmYhPPsmwfns33rnHmNBiptOgKaBoVDQAjRioTf94mnmefx9pp9wuO1qAWoUrsVsFQBDRX6cUMZCxKfdSpAJfkscE3ERwwjARdJ5BJA4M17wics21Z7cwSVBWsEdSg/DEgJhOmK0GiaHHqrAMNUdSteE3h5foQTErJQ5WHf5Fqxz447NmTlCFa0IGsIGCRLDIbsk8O3smts9zNHdGzY3oQeL6UGc3Md8+CPzeQoIURLoBahBfNb1Y6JX/eezobWkCiIQJJ4I1DajgAq2vv795c3CfBpx3VPYjJXlHeUqeefAjnlKxOQlOf102coyrkI/dfsR4ABAH9bW8vhkbgyAAAAAElFTkSuQmCC",
    sets: ["all"],
    all: [">", "1", "2", "3", "4", "5", "6", "7", "8", "9", "0", "-", "=", "backspace", "EOL",
        "tab", "й", "ц", "у", "к", "е", "н", "г", "ш", "щ", "з", "х", "ъ", "return", "EOL",
        "{capslock}", "ф", "ы", "в", "а", "п", "р", "о", "л", "д", "ж", "э", "ё", "EOL",
        "[shift]", "]", "я", "ч", "с", "м", "и", "т", "ь", "б", "ю", "/", "[rightshift]", "EOL",
        "selector", "[alt]", "space", "[alt]", "EOL"],
    all_shift: ["<", "!", "'", "№", "%", ":", ",", ".", ";", "(", ")", "_", "+", "backspace", "EOL",
        "tab", "Й", "Ц", "У", "К", "Е", "Н", "Г", "Ш", "Щ", "З", "Х", "Ъ", "return", "EOL",
        "{capslock}", "Ф", "Ы", "В", "А", "П", "Р", "О", "Л", "Д", "Ж", "Э", "Ё", "EOL",
        "[shift]", "[", "Я", "Ч", "С", "М", "И", "Т", "Ь", "Б", "Ю", "?", "[rightshift]", "EOL",
        "selector", "[alt]", "space", "[alt]", "EOL"],
    all_capslock: [">", "1", "2", "3", "4", "5", "6", "7", "8", "9", "0", "-", "=", "backspace", "EOL",
        "tab", "Й", "Ц", "У", "К", "Е", "Н", "Г", "Ш", "Щ", "З", "Х", "Ъ", "return", "EOL",
        "{capslock}", "Ф", "Ы", "В", "А", "П", "Р", "О", "Л", "Д", "Ж", "Э", "Ё", "EOL",
        "[shift]", "[", "Я", "Ч", "С", "М", "И", "Т", "Ь", "Б", "Ю", "?", "[rightshift]", "EOL",
        "selector", "[alt]", "space", "[alt]", "EOL"],    
    all_alt: ["§", "!", "@", "#", "$", "%", "^", "&", "*", "(", ")", "–", "»", "backspace", "EOL",
        "tab", "ј", "џ", "ќ", "®", "†", "њ", "ѓ", "ѕ", "ў", "‘", "“", "ъ", "return", "EOL",
        "{capslock}", "ƒ","ы","ћ","÷","©","}","°","љ","∆","…","э","ё", "EOL",
        "[shift]", "]","ђ","≈","≠","µ","и","™","~","≤","≥","“", "[rightshift]", "EOL",
        "selector", "[alt]", "space", "[alt]", "EOL"],
    all_alt_shift: ["±","|","'","£","€","∞","¬","¶","√","\'","`","—","«", "backspace", "EOL",
        "tab","Ј","Џ","Ќ","®","†","Њ","Ѓ","Ѕ","Ў","’","”","Ъ", "return", "EOL",
        "{capslock}", "ƒ","Ы","Ћ","÷","©","{","•","Љ","∆","…","Э","Ё", "EOL",
        "[shift]", "[","Ђ","≈","≠","µ","И","™","~","<",">","„", "[rightshift]", "EOL",
        "selector", "[alt]", "space", "[alt]", "EOL"],
    all_alt_capslock: ["§", "!", "@", "#", "$", "%", "^", "&", "*", "(", ")", "–", "»", "backspace", "EOL",
        "tab","Ј","Џ","Ќ","®","†","Њ","Ѓ","Ѕ","Ў","’","”","Ъ", "return", "EOL",
        "{capslock}", "ƒ","Ы","Ћ","÷","©","{","•","Љ","∆","…","Э","Ё", "EOL",
        "[shift]", "[","Ђ","≈","≠","µ","И","™","~","<",">","„", "[rightshift]", "EOL",
        "selector", "[alt]", "space", "[alt]", "EOL"],
    all_shift_alt: ["all_alt_shift"],
    all_capslock_alt: ["all_alt_capslock"],
    all_shift_capslock: ["all_shift"],
    all_capslock_shift: ["all_shift"],    
    all_alt_capslock_shift: ["all_alt_shift"],
    all_alt_shift_capslock: ["all_alt_shift"],
    all_shift_alt_capslock: ["all_alt_shift"],
    all_capslock_alt_shift: ["all_alt_shift"],
    all_capslock_shift_alt: ["all_alt_shift"],
    all_shift_capslock_alt: ["all_alt_shift"]
};

layouts["de"] = {
    name: "Deutsch",
    icon: "iVBORw0KGgoAAAANSUhEUgAAACAAAAAcCAYAAAAAwr0iAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAA2RpVFh0WE1MOmNvbS5hZG9iZS54bXAAAAAAADw/eHBhY2tldCBiZWdpbj0i77u/IiBpZD0iVzVNME1wQ2VoaUh6cmVTek5UY3prYzlkIj8+IDx4OnhtcG1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iIHg6eG1wdGs9IkFkb2JlIFhNUCBDb3JlIDUuMC1jMDYwIDYxLjEzNDc3NywgMjAxMC8wMi8xMi0xNzozMjowMCAgICAgICAgIj4gPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4gPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIgeG1sbnM6eG1wTU09Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9tbS8iIHhtbG5zOnN0UmVmPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvc1R5cGUvUmVzb3VyY2VSZWYjIiB4bWxuczp4bXA9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC8iIHhtcE1NOk9yaWdpbmFsRG9jdW1lbnRJRD0ieG1wLmRpZDpDRTUxMjNGN0Q5RDJFMDExQkI3QkRGOUNFMzAzQThBQSIgeG1wTU06RG9jdW1lbnRJRD0ieG1wLmRpZDozRUM2QzdFMjVGREQxMUUyQkM2MDk5QzBCRTQyNjExQiIgeG1wTU06SW5zdGFuY2VJRD0ieG1wLmlpZDozRUM2QzdFMTVGREQxMUUyQkM2MDk5QzBCRTQyNjExQiIgeG1wOkNyZWF0b3JUb29sPSJBZG9iZSBQaG90b3Nob3AgQ1M1IFdpbmRvd3MiPiA8eG1wTU06RGVyaXZlZEZyb20gc3RSZWY6aW5zdGFuY2VJRD0ieG1wLmlpZDo1OUVDNTc3RkQzNUZFMjExQjZCMkMzMkRFRjFGMDVEQSIgc3RSZWY6ZG9jdW1lbnRJRD0ieG1wLmRpZDpDRTUxMjNGN0Q5RDJFMDExQkI3QkRGOUNFMzAzQThBQSIvPiA8L3JkZjpEZXNjcmlwdGlvbj4gPC9yZGY6UkRGPiA8L3g6eG1wbWV0YT4gPD94cGFja2V0IGVuZD0iciI/PvPidRkAAAIZSURBVHjaxJfJjuIwEIZ/h2QCLXVGQoK+cBpxbdFnHnneYp5hJK5IwA2JQxKyObanChKC09DqOWAs2ZaXpL5yVXkRxhg8M3l4cvKXy+VgNpuFk8lkEIYhPO+xTFprlGWJ/X6vdrtd6cdxHM3n88N0OsVoNIIQ4qEAbPI8zzEej7Farcb+er3+SSRYLBYYDodOAIqiwHa7Bcv2sywLGWCz2aCqKhAB+gjspoIKQ0U7eupr6sss04yKtqfpE90UTQBhGIBlsmy/tcvhcACZw4njRVF0VpadkAsp5ckunF2kIAhsgLqukaYpjsejm9inSGOZFkCSJBcA05nRbtkD/+N6nz60VuB3/QNhLCEy5WQFjJKQhYdfLQBkDU0mEHl5h7yvQT8GxB1Nb39vtIIhv7usADd0nECU5Y0f9ndG3dvFbwnp99m1kRVMdQ1APmCSlMPBjQmqAGYw6ABYsDpm8BwBaApDRK8dgKYV8Gqyi9JuVkAo6Kq2TSD4XqDdALAsjgQLAA4BWJYVBW9/FF6GAt7lJPl81NjRgRtj+CI07bamAyorSNmP1gdOmg+ayeYLAeYbO969uXZbqSsf0FpdAbhJ2uhuN1Hs/Q++iNiWEtBNxPlnAAOKwtOlw00YNkq3AJXUyAt2zhdXC4BSdgCqoCMgzVK4eiIwgH/eiRUb/o3yO+WJ4yfBnvJfBggpvza1y8RHbyKe/TT7J8AAdWw5OED9CTEAAAAASUVORK5CYII=",
    sets: ["all"],
    all: ["[^]","1","2","3","4","5","6","7","8","9","0","ß","[´]","backspace","EOL",
        "tab","q","w","e","r","t","z","u","i","o","p","ü","+","return","EOL",
        "{capslock}","a","s","d","f","g","h","j","k","l","ö","ä","#","EOL",
        "[shift]","<","y","x","c","v","b","n","m",",",".","-","[rightshift]","EOL",
        "selector","[alt]","space","[alt]","EOL"],
    all_shift: ["°","!","'","§","$","%","&","/","(",")","=","?","[`]","backspace","EOL",
        "tab","Q","W","E","R","T","Z","U","I","O","P","Ü","*","return","EOL",
        "{capslock}","A","S","D","F","G","H","J","K","L","Ö","Ä","\'","EOL",
        "[shift]",">","Y","X","C","V","B","N","M",";",":","_","[rightshift]","EOL",
        "selector","[alt]","space","[alt]","EOL"],
    all_capslock: ["[^]","1","2","3","4","5","6","7","8","9","0","ß","[´]","backspace","EOL",
        "tab","Q","W","E","R","T","Z","U","I","O","P","Ü","*","return","EOL",
        "{capslock}","A","S","D","F","G","H","J","K","L","Ö","Ä","\'","EOL",
        "[shift]",">","Y","X","C","V","B","N","M",";",":","_","[rightshift]","EOL",
        "selector","[alt]","space","[alt]","EOL"],    
    all_alt: ["„","¡","“","¶","¢","[","]","|","{","}","≠","¿","\'","backspace","EOL",
        "tab","«","∑","€","†","≈","Ω","¨","⁄","ø","π","•","±","return","EOL",
        "{capslock}","å","‚","∂","ƒ","©","ª","º","∆","@","œ","æ","‘","EOL",
        "[shift]","≤","¥","≈","ç","√","∫","~","µ","∞","…","–","[rightshift]","EOL",
        "selector","[alt]","space","[alt]","EOL"],
    all_alt_shift: ["“","¬","”","#","£","ﬁ","^","\\","˜","·","¯","˙","˚","backspace","EOL",
        "tab","»","„","‰","¸","˝","ˇ","Á","Û","Ø","∏","°","","return","EOL",
        "{capslock}","Å","Í","™","Ï","Ì","Ó","ı","ˆ","ﬂ","Œ","Æ","’","EOL",
        "[shift]","≥","‡","Ù","Ç","◊","‹","›","˘","˛","÷","—","[rightshift]","EOL",
        "selector","[alt]","space","[alt]","EOL"],
    all_alt_capslock: ["„","¡","“","¶","¢","[","]","|","{","}","≠","¿","\'","backspace","EOL",
        "tab","»","„","‰","¸","˝","ˇ","Á","Û","Ø","∏","°","","return","EOL",
        "{capslock}","Å","Í","™","Ï","Ì","Ó","ı","ˆ","ﬂ","Œ","Æ","’","EOL",
        "[shift]","≥","‡","Ù","Ç","◊","‹","›","˘","˛","÷","—","[rightshift]","EOL",
        "selector","[alt]","space","[alt]","EOL"],
    "all_^": ["[^]", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "backspace", "EOL",
        "tab", "empty", "empty", "ê", "empty", "empty", "empty", "û", "î", "ô", "empty", "empty", "empty", "return", "EOL",
        "{capslock}", "â", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "EOL",
        "[shift]", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "[rightshift]", "EOL",
        "selector", "[alt]", "space", "[alt]", "EOL"],    
    "all_^_shift": ["[^]", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "backspace", "EOL",
        "tab", "empty", "empty", "Ê", "empty", "empty", "empty", "Û", "Î", "Ô", "empty", "empty", "empty", "return", "EOL",
        "{capslock}", "Â", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "EOL",
        "[shift]", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "[rightshift]", "EOL",
        "selector", "[alt]", "space", "[alt]", "EOL"],    
    "all_`": ["empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "[`]", "backspace", "EOL",
        "tab", "empty", "empty", "è", "empty", "empty", "empty", "ù", "ì", "ò", "empty", "empty", "empty", "return", "EOL",
        "{capslock}", "à", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "EOL",
        "[shift]", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "[rightshift]", "EOL",
        "selector", "[alt]", "space", "[alt]", "EOL"],    
    "all_`_shift": ["empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "[`]", "backspace", "EOL",
        "tab", "empty", "empty", "È", "empty", "empty", "empty", "Ù", "Ì", "Ò", "empty", "empty", "empty", "return", "EOL",
        "{capslock}", "À", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "EOL",
        "[shift]", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "[rightshift]", "EOL",
        "selector", "[alt]", "space", "[alt]", "EOL"],
    "all_´": ["empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "[´]", "backspace", "EOL",
        "tab", "empty", "empty", "é", "empty", "empty", "empty", "ú", "í", "ó", "empty", "empty", "empty", "return", "EOL",
        "{capslock}", "á", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "EOL",
        "[shift]", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "[rightshift]", "EOL",
        "selector", "[alt]", "space", "[alt]", "EOL"],    
    "all_´_shift": ["empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "[´]", "backspace", "EOL",
        "tab", "empty", "empty", "É", "empty", "empty", "empty", "Ú", "Ì", "Ò", "empty", "empty", "empty", "return", "EOL",
        "{capslock}", "À", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "EOL",
        "[shift]", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "[rightshift]", "EOL",
        "selector", "[alt]", "space", "[alt]", "EOL"],
    all_shift_capslock: ["all_shift"],
    all_capslock_shift: ["all_shift"],    
    "all_shift_`": ["all_`_shift"],
    "all_capslock_`": ["all_`_shift"],
    "all_`_capslock": ["all_`_shift"],    
    "all_alt_^": ["all_^"],
    "all_^_alt": ["all_^"],    
    "all_alt_^_shift": ["all_^_shift"],
    "all_^_alt_shift": ["all_^_shift"],    
    "all_alt_^_capslock": ["all_^_shift"],
    "all_^_alt_capslock": ["all_^_shift"],    
    "all_shift_^": ["all_^_shift"],
    "all_capslock_^": ["all_^_shift"],
    "all_^_capslock": ["all_^_shift"],    
    "all_shift_´": ["all_´_shift"],
    "all_capslock_´": ["all_´_shift"],
    "all_´_capslock": ["all_´_shift"],    
    all_shift_alt: ["all_alt_shift"],
    all_capslock_alt: ["all_alt_capslock"],
    all_alt_capslock_shift: ["all_alt_shift"],
    all_alt_shift_capslock: ["all_alt_shift"],
    all_shift_alt_capslock: ["all_alt_shift"],
    all_capslock_alt_shift: ["all_alt_shift"],
    all_capslock_shift_alt: ["all_alt_shift"],
    all_shift_capslock_alt: ["all_alt_shift"]
};

layouts["es"] = {
    name: "Español",
    icon: "iVBORw0KGgoAAAANSUhEUgAAACAAAAAcCAYAAAAAwr0iAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAA2RpVFh0WE1MOmNvbS5hZG9iZS54bXAAAAAAADw/eHBhY2tldCBiZWdpbj0i77u/IiBpZD0iVzVNME1wQ2VoaUh6cmVTek5UY3prYzlkIj8+IDx4OnhtcG1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iIHg6eG1wdGs9IkFkb2JlIFhNUCBDb3JlIDUuMC1jMDYwIDYxLjEzNDc3NywgMjAxMC8wMi8xMi0xNzozMjowMCAgICAgICAgIj4gPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4gPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIgeG1sbnM6eG1wTU09Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9tbS8iIHhtbG5zOnN0UmVmPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvc1R5cGUvUmVzb3VyY2VSZWYjIiB4bWxuczp4bXA9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC8iIHhtcE1NOk9yaWdpbmFsRG9jdW1lbnRJRD0ieG1wLmRpZDpDRTUxMjNGN0Q5RDJFMDExQkI3QkRGOUNFMzAzQThBQSIgeG1wTU06RG9jdW1lbnRJRD0ieG1wLmRpZDozRUM2QzdFNjVGREQxMUUyQkM2MDk5QzBCRTQyNjExQiIgeG1wTU06SW5zdGFuY2VJRD0ieG1wLmlpZDozRUM2QzdFNTVGREQxMUUyQkM2MDk5QzBCRTQyNjExQiIgeG1wOkNyZWF0b3JUb29sPSJBZG9iZSBQaG90b3Nob3AgQ1M1IFdpbmRvd3MiPiA8eG1wTU06RGVyaXZlZEZyb20gc3RSZWY6aW5zdGFuY2VJRD0ieG1wLmlpZDo1OUVDNTc3RkQzNUZFMjExQjZCMkMzMkRFRjFGMDVEQSIgc3RSZWY6ZG9jdW1lbnRJRD0ieG1wLmRpZDpDRTUxMjNGN0Q5RDJFMDExQkI3QkRGOUNFMzAzQThBQSIvPiA8L3JkZjpEZXNjcmlwdGlvbj4gPC9yZGY6UkRGPiA8L3g6eG1wbWV0YT4gPD94cGFja2V0IGVuZD0iciI/Plh1LYUAAANASURBVHjaxFfLahRBFD1VXZ2evCYT4+RlUAwRI6LRha9AluJG3Lly4cala5f+hrgQxF/wBW4UFy6igiJGwUdIHKMyYzSdzGS6p7qut6ZnMm1A0MR0Cm5Xd1Hddeqc+6gWRITtbBLb3NTk5KQzMjLi5fN5x/M8SLm1mIwxCIIAxWIxKhQKgfJ9P3t9bP+i7O+HbG8HhNjaLbPkZnUVZkc/pmZmdqjZ2dkeXVhAx8QERCaTCgBZrSL4VIBdW1UqFS8sfEbb/CdQGCYANHtqdaI5Tok5CSdeG068S83nxj0ZCJa6xmvatZWdFrEuevEH4PvpeF42Cx3WYiesX2sh61IBWJtUmqtgLNtNAKQNaKUMlMspBT9HmtYtAEP3NFTbMqRYB0DEFkWiLp9y+Gr+QyjyZ3QtAPqaEsDqscyWkEAQg1Qor3Ti5xdZx5IbjtDRWYZSEdO2mWjhXVCQ8AELgCyAamuOA4RLHkrXGJSIQFGEIifOwcsu5M4AUm8mFHVj02sAeIDKawCIdzd9o4p9pxS6Trr4/lRBHdiN3mMR/OIcnt1dxdSFTJzHbS3529zRnEvMIJIMUIMBEaMSTPH4xbNwpp9g/mYJmcwAcmNXEDypInfuFg7vUuxHD9g51O/x/1cgrHEEkFzPwFIMxJLzTaP6mJG+WMLHToJfreHIwhwGh/eh/EhzznDRdaYEN9e2QQlcmwxa1ZCM1SSKncOaS6AKwWXKT+S/432hHbfv3ELw8iqw8o6n8AcUteb/s7FPUcIH6g9WH4pjTIoQuTMDaOt2oUsGl+QLFKYN5p8bHD1/EJQfZOSWNWfD9YBMrcWAqTPQ2lHoZXH/zRu8/dgO8iRqoyfg7TmOviGFOS3x8MNraK9zEwxwRTQJBmyNbgEQcGWIidEZ9GZ/ILvXgVotoe80oSej4MsSOpYjqHocrs9K6wsV/vBsAdDa6P5XXs/bDseBSKkWEJ87yibC4erSeMwAJxkwAKR4Pqyv2fSBiNFs+UHkN6VEQ/aGD2h7TBIClNr6AjoJoMYAbBKmrq50ALCFDbktgCjgvX9d8dNjIK51dfXt/QDbIbZ8yr8ERbZXFoDH1t3o02y2HC6L7f41+yXAAGQsmY8ApwdZAAAAAElFTkSuQmCC",
    sets: ["all"],
    all: ["[","1","2","3","4","5","6","7","8","9","0","-","=","backspace","EOL",
        "tab","q","w","e","r","t","y","u","i","o","p","[´]","[`]","return","EOL",
        "{capslock}","a","s","d","f","g","h","j","k","l","ñ",";","\'","EOL",
        "[shift]","<","z","x","c","v","b","n","m",",",".","ç","[rightshift]","EOL",
        "selector","[alt]","space","[alt]","EOL"],
    all_shift: ["]","¡","!","#","$","%","/","&","*","(",")","_","+","backspace","EOL",
        "tab","Q","W","E","R","T","Y","U","I","O","P","º","¨","return","EOL",
        "{capslock}","A","S","D","F","G","H","J","K","L","Ñ",":","'","EOL",
        "[shift]",">","Z","X","C","V","B","N","M","¿","?","Ç","[rightshift]","EOL",
        "selector","[alt]","space","[alt]","EOL"],
    all_alt: ["{","‘","“","«","¢","∞","\\","|","°","£","≠","–","±","backspace","EOL",
        "tab","œ","∑","æ","®","†","¥","€","[^]","ø","π","ª","|","return","EOL",
        "{capslock}","å","ß","∂","ƒ","@","™","∆","§","¬","~","¶","]","EOL",
        "[shift]","[","Ω","≈","©","√","∫",">","µ","Ÿ","…","•","[rightshift]","EOL",
        "selector","[alt]","space","[alt]","EOL"],
    all_alt_shift: ["}","’","”","»","Î","Ì","Ï","Í","","Ô","Ò","—","Ó","backspace","EOL",
        "tab","Œ","Ê","Æ","È","‰","Ë","Û","ı","Ø","∏","Ù","Ú","return","EOL",
        "{capslock}","Å","ﬁ","ﬂ","‡","‚","·","˜","˘","ˆ","˙","¯","}","EOL",
        "[shift]","{","„","‰","Â","◊","<",">","≤","≥","÷","¸","[rightshift]","EOL",
        "selector","[alt]","space","[alt]","EOL"],
    all_capslock: ["[","1","2","3","4","5","6","7","8","9","0","-","=","backspace","EOL",
        "tab","Q","W","E","R","T","Y","U","I","O","P","º","¨","return","EOL",
        "{capslock}","A","S","D","F","G","H","J","K","L","Ñ",":","'","EOL",
        "[shift]",">","Z","X","C","V","B","N","M","¿","?","Ç","[rightshift]","EOL",
        "selector","[alt]","space","[alt]","EOL"],
    all_alt_capslock: ["{","‘","“","«","¢","∞","\\","|","°","£","≠","–","±","backspace","EOL",
        "tab","Œ","Ê","Æ","È","‰","Ë","Û","ı","Ø","∏","Ù","Ú","return","EOL",
        "{capslock}","Å","ﬁ","ﬂ","‡","‚","·","˜","˘","ˆ","˙","¯","}","EOL",
        "[shift]","{","„","‰","Â","◊","<",">","≤","≥","÷","¸","[rightshift]","EOL",
        "selector","[alt]","space","[alt]","EOL"],
    "all_`": ["empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "backspace", "EOL",
        "tab", "empty", "empty", "è", "empty", "empty", "empty", "ù", "ì", "ò", "empty", "empty", "[`]", "return", "EOL",
        "{capslock}", "à", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "EOL",
        "[shift]", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "[rightshift]", "EOL",
        "selector", "[alt]", "space", "[alt]", "EOL"],
    "all_`_shift": ["empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "backspace", "EOL",
        "tab", "empty", "empty", "È", "empty", "empty", "empty", "Ù", "Ì", "Ò", "empty", "empty", "[`]", "return", "EOL",
        "{capslock}", "À", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "EOL",
        "[shift]", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "[rightshift]", "EOL",
        "selector", "[alt]", "space", "[alt]", "EOL"],
    "all_´": ["empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "backspace", "EOL",
        "tab", "empty", "empty", "é", "empty", "empty", "empty", "ú", "í", "ó", "empty", "[´]", "empty", "return", "EOL",
        "{capslock}", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "EOL",
        "[shift]", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "[rightshift]", "EOL",
        "selector", "[alt]", "space", "[alt]", "EOL"],
    "all_´_shift": ["empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "backspace", "EOL",
                   "tab", "empty", "empty", "È", "empty", "empty", "empty", "Ù", "Ì", "Ò", "empty", "[´]", "empty", "return", "EOL",
                   "{capslock}", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "EOL",
                   "[shift]", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "[rightshift]", "EOL",
                   "selector", "[alt]", "space", "[alt]", "EOL"],        
    "all_^": ["empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "backspace", "EOL",
        "tab", "empty", "empty", "ê", "empty", "empty", "empty", "û", "î", "ô", "[^]", "empty", "empty", "return", "EOL",
        "{capslock}", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "EOL",
        "[shift]", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "[rightshift]", "EOL",
        "selector", "[alt]", "space", "[alt]", "EOL"],
    "all_^_shift": ["empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "backspace", "EOL",
        "tab", "empty", "empty", "Ê", "empty", "empty", "empty", "Û", "Î", "Ô", "[^]", "empty", "empty", "return", "EOL",
        "{capslock}", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "EOL",
        "[shift]", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "[rightshift]", "EOL",
        "selector", "[alt]", "space", "[alt]", "EOL"],
    "all_shift_`": ["all_`_shift"],
    "all_capslock_`": ["all_`_shift"],
    "all_`_capslock": ["all_`_shift"],    
    all_shift_capslock: ["all_shift"],
    all_capslock_shift: ["all_shift"],
    "all_alt_^": ["all_^"],
    "all_^_alt": ["all_^"],    
    "all_alt_^_shift": ["all_^_shift"],
    "all_^_alt_shift": ["all_^_shift"],    
    "all_alt_^_capslock": ["all_^_shift"],
    "all_^_alt_capslock": ["all_^_shift"],    
    "all_shift_^": ["all_^_shift"],
    "all_capslock_^": ["all_^_shift"],
    "all_^_capslock": ["all_^_shift"],    
    "all_shift_´": ["all_´_shift"],
    "all_capslock_´": ["all_´_shift"],
    "all_´_capslock": ["all_´_shift"],    
    all_shift_alt: ["all_alt_shift"],
    all_capslock_alt: ["all_alt_capslock"],
    all_alt_capslock_shift: ["all_alt_shift"],
    all_alt_shift_capslock: ["all_alt_shift"],
    all_shift_alt_capslock: ["all_alt_shift"],
    all_capslock_alt_shift: ["all_alt_shift"],
    all_capslock_shift_alt: ["all_alt_shift"],
    all_shift_capslock_alt: ["all_alt_shift"]
};

layouts["fr"] = {
    name: "Français",
    icon: "iVBORw0KGgoAAAANSUhEUgAAACAAAAAcCAYAAAAAwr0iAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAA2RpVFh0WE1MOmNvbS5hZG9iZS54bXAAAAAAADw/eHBhY2tldCBiZWdpbj0i77u/IiBpZD0iVzVNME1wQ2VoaUh6cmVTek5UY3prYzlkIj8+IDx4OnhtcG1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iIHg6eG1wdGs9IkFkb2JlIFhNUCBDb3JlIDUuMC1jMDYwIDYxLjEzNDc3NywgMjAxMC8wMi8xMi0xNzozMjowMCAgICAgICAgIj4gPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4gPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIgeG1sbnM6eG1wTU09Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9tbS8iIHhtbG5zOnN0UmVmPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvc1R5cGUvUmVzb3VyY2VSZWYjIiB4bWxuczp4bXA9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC8iIHhtcE1NOk9yaWdpbmFsRG9jdW1lbnRJRD0ieG1wLmRpZDpDRTUxMjNGN0Q5RDJFMDExQkI3QkRGOUNFMzAzQThBQSIgeG1wTU06RG9jdW1lbnRJRD0ieG1wLmRpZDozRUYwNDlFRjVGREQxMUUyQkM2MDk5QzBCRTQyNjExQiIgeG1wTU06SW5zdGFuY2VJRD0ieG1wLmlpZDozRUYwNDlFRTVGREQxMUUyQkM2MDk5QzBCRTQyNjExQiIgeG1wOkNyZWF0b3JUb29sPSJBZG9iZSBQaG90b3Nob3AgQ1M1IFdpbmRvd3MiPiA8eG1wTU06RGVyaXZlZEZyb20gc3RSZWY6aW5zdGFuY2VJRD0ieG1wLmlpZDo1OUVDNTc3RkQzNUZFMjExQjZCMkMzMkRFRjFGMDVEQSIgc3RSZWY6ZG9jdW1lbnRJRD0ieG1wLmRpZDpDRTUxMjNGN0Q5RDJFMDExQkI3QkRGOUNFMzAzQThBQSIvPiA8L3JkZjpEZXNjcmlwdGlvbj4gPC9yZGY6UkRGPiA8L3g6eG1wbWV0YT4gPD94cGFja2V0IGVuZD0iciI/PnftpCkAAAJPSURBVHjaxJfLbtNAFIZ/3+QWhSAhJbAIu26h+0jsWHfPC/St2PJCSJFYRarcBhTJrRxfMp4bM2MnxFUzNjA0Rz52FGt8Pp//zJmxJ6XEKc3HiS2cz+fBbDaLJ5NJEMcxfP//MgkhQAjBer3mSZKQMMuy8cXF53Q6HeP8PILneUcHX19/HBQk/fL16D0tuay2YNN7fFosXofL5fJVkjzg8vIdzs7sAIPT+nYCCwHEdgua3EHHDsuyjJPkHjc3KeqaQRHgMYIuU0+drq4+DALYLr7vgxnTL9X+lkLCjyOQ2zvo2GGjC0Oa5siyrROd6e0P631vPAKjtMmWGUAFqooad2FaY7tGIaTO9g6AMY48JyiK2gkAL0p7BnwPknUABDabag9gNP+XqdYDYGKQupsBrX9ZOpKgD0D1gg4ApY0EVcWeqv8/zgnPS/t49cKC1t0i1BkgZAewG4S/EkOU5dEeoKek5PSxBEzVQJMJJ+22KOwS1RFE2/L3GSiK3FydzIL0wQ4QRYDqBZ0iZEyCc0dLs5AHNfAUoa4B2pVALxJCuAGQwp5JE6uV2wBwlQEpfWcA6AEwC1JnFjBuqt3Z7kgDeMcVMACCH0ogEQRwJ4F+Eduj1FRk9KAVc84UQOQuAwOeIzj/vSfU2yQXG5HBpmKJtk7CBlgD6D/sxUPpsLWCQfbFB+8CcBN8NAqsA4ueDrczMnphB1BetzJpAK6PPE+BHvLVajUI4GeW9QIEzRrD9fmN8vfKJ8/8SbBW/k0DxMpfttfnNKJ845360+yXAAMAZl9qDcR+X2AAAAAASUVORK5CYII=",
    sets: ["all"],
    all: ["@", "&", "é", "'", "\"", "(", "§", "è", "!", "ç", "à", ")", "-", "backspace", "EOL",
        "tab", "a", "z", "e", "r", "t", "y", "u", "i", "o", "p", "[^]", "$", "return", "EOL",
        "{capslock}", "q", "s", "d", "f", "g", "h", "j", "k", "l", "m", "ù", "[`]", "EOL",
        "[shift]", "<", "w", "x", "c", "v", "b", "n", ",", ";", ":", "=", "[rightshift]", "EOL",
        "selector", "[alt]", "space", "[alt]", "EOL"],
    all_alt: ["•", "","ë","“","‘","{","¶","«","¡","Ç","ø","}","—", "backspace", "EOL",
        "tab", "æ", "Â", "ê", "®", "†", "Ú", "º", "î", "œ", "π", "ô", "€", "return", "EOL",
        "{capslock}", "‡", "Ò", "∂", "ƒ", "ﬁ", "Ì", "Ï", "È", "¬", "µ", "Ù", "@", "EOL",
        "[shift]", "≤", "‹", "≈", "©", "◊", "ß", "~", "∞", "…", "÷", "≠", "[rightshift]" ,"EOL",
        "selector", "[alt]" , "space", "[alt]", "EOL"],
    all_shift: ["#", "1", "2", "3", "4", "5", "6", "7", "8", "9", "0", "°", "_", "backspace", "EOL",
        "tab", "A", "Z", "E", "R", "T", "Y", "U", "I", "O", "P", "[¨]", "*", "return", "EOL",
        "{capslock}", "Q", "S", "D", "F", "G", "H", "J", "K", "L", "M", "%", "£", "EOL",
        "[shift]", ">", "W", "X", "C", "V", "B", "N", "?", ".", "/", "+", "[rightshift]", "EOL",
        "selector", "[alt]", "space", "[alt]", "EOL"],
    all_capslock: ["@", "&", "é", "'", "\'", "(", "§", "è", "!", "ç", "à", ")", "-", "backspace", "EOL",
        "tab", "A", "Z", "E", "R", "T", "Y", "U", "I", "O", "P", "[¨]", "*", "return", "EOL",
        "{capslock}", "Q", "S", "D", "F", "G", "H", "J", "K", "L", "M", "%", "£", "EOL",
        "[shift]", ">", "W", "X", "C", "V", "B", "N", "?", ".", "/", "+", "[rightshift]", "EOL",
        "selector", "[alt]", "space", "[alt]", "EOL"],
    all_alt_shift: ["Ÿ","[´]","„","”","’","[","å","»","Û","Á","Ø","]","–","backspace","EOL",
        "tab", "Æ","Å","Ê","‚","™","Ÿ","ª","ï","Œ","∏","Ô","¥", "return","EOL",
        "{capslock}", "Ω","∑","∆","·","·","ﬂ","Î","Í","Ë","|","Ó","‰", "EOL",
        "[shift]", "≥","›","⁄","¢","√","∫","ı","¿","•","\\","±","[rightshift]", "EOL",
        "selector", "[alt]", "space", "[alt]", "EOL"],
    all_alt_capslock: ["•", "","ë","“","‘","{","¶","«","¡","Ç","ø","}","—", "backspace", "EOL",
        "tab", "Æ","Å","Ê","‚","™","Ÿ","ª","ï","Œ","∏","Ô","¥", "return","EOL",
        "{capslock}", "Ω","∑","∆","·","·","ﬂ","Î","Í","Ë","|","Ó","‰", "EOL",
        "[shift]", "≥","›","⁄","¢","√","∫","ı","¿","•","\\","±","[rightshift]", "EOL",
        "selector", "[alt]", "space", "[alt]", "EOL"],
    "all_^": ["empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "backspace", "EOL",
        "tab", "â", "empty", "ê", "empty", "empty", "empty", "û", "î", "ô", "empty", "[^]", "empty", "return", "EOL",
        "{capslock}", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "EOL",
        "[shift]", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "[rightshift]", "EOL",
        "selector", "[alt]", "space", "[alt]", "EOL"],
    "all_^_shift": ["empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "backspace", "EOL",
        "tab", "Â", "empty", "Ê", "empty", "empty", "empty", "Û", "Î", "Ô", "empty", "[^]", "empty", "return", "EOL",
        "{capslock}", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "EOL",
        "[shift]", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "[rightshift]", "EOL",
        "selector", "[alt]", "space", "[alt]", "EOL"],
    "all_`": ["empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "backspace", "EOL",
        "tab", "à", "empty", "è", "empty", "empty", "empty", "ù", "ì", "ò", "empty", "empty", "empty", "return", "EOL",
        "{capslock}", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "[`]", "EOL",
        "[shift]", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "[rightshift]", "EOL",
        "selector", "[alt]", "space", "[alt]", "EOL"],
    "all_`_shift": ["empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "backspace", "EOL",
        "tab", "À", "empty", "È", "empty", "empty", "empty", "Ù", "Ì", "Ò", "empty", "empty", "empty", "return", "EOL",
        "{capslock}", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "[`]", "EOL",
        "[shift]", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "[rightshift]", "EOL",
        "selector", "[alt]", "space", "[alt]", "EOL"],
    "all_´": ["empty", "[´]", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "backspace", "EOL",
        "tab", "á", "empty", "é", "empty", "empty", "empty", "ú", "í", "ó", "empty", "empty", "empty", "return", "EOL",
        "{capslock}", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "EOL",
        "[shift]", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "[rightshift]", "EOL",
        "selector", "[alt]", "space", "[alt]", "EOL"],
    "all_´_shift": ["empty", "[´]", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "backspace", "EOL",
        "tab", "À", "empty", "È", "empty", "empty", "empty", "Ù", "Ì", "Ò", "empty", "empty", "empty", "return", "EOL",
        "{capslock}", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "EOL",
        "[shift]", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "[rightshift]", "EOL",
        "selector", "[alt]", "space", "[alt]", "EOL"],
    "all_shift_^": ["all_^_shift"],
    "all_capslock_^": ["all_^_shift"],
    "all_^_capslock": ["all_^_shift"],    
    "all_shift_capslock": ["all_shift"],
    "all_capslock_shift": ["all_shift"],    
    "all_shift_`": ["all_`_shift"],
    "all_capslock_`": ["all_`_shift"],
    "all_`_capslock": ["all_`_shift"],    
    "all_shift_´": ["all_´_shift"],
    "all_capslock_´": ["all_´_shift"],
    "all_´_capslock": ["all_´_shift"],    
    "all_alt_´_shift": ["all_´"],
    "all_alt_shift_´": ["all_´"],
    "all_shift_alt_´": ["all_´"],
    "all_´_alt_shift": ["all_´"],
    "all_´_shift_alt": ["all_´"],
    "all_shift_´_alt": ["all_´"],
    all_shift_alt: ["all_alt_shift"],
    all_capslock_alt: ["all_alt_capslock"],
    all_alt_capslock_shift: ["all_alt_shift"],
    all_alt_shift_capslock: ["all_alt_shift"],
    all_shift_alt_capslock: ["all_alt_shift"],
    all_capslock_alt_shift: ["all_alt_shift"],
    all_capslock_shift_alt: ["all_alt_shift"],
    all_shift_capslock_alt: ["all_alt_shift"]
};

layouts["it"] = {
    name: "Italiano",
    icon: "iVBORw0KGgoAAAANSUhEUgAAACAAAAAcCAYAAAAAwr0iAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAA2RpVFh0WE1MOmNvbS5hZG9iZS54bXAAAAAAADw/eHBhY2tldCBiZWdpbj0i77u/IiBpZD0iVzVNME1wQ2VoaUh6cmVTek5UY3prYzlkIj8+IDx4OnhtcG1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iIHg6eG1wdGs9IkFkb2JlIFhNUCBDb3JlIDUuMC1jMDYwIDYxLjEzNDc3NywgMjAxMC8wMi8xMi0xNzozMjowMCAgICAgICAgIj4gPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4gPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIgeG1sbnM6eG1wTU09Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9tbS8iIHhtbG5zOnN0UmVmPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvc1R5cGUvUmVzb3VyY2VSZWYjIiB4bWxuczp4bXA9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC8iIHhtcE1NOk9yaWdpbmFsRG9jdW1lbnRJRD0ieG1wLmRpZDpDRTUxMjNGN0Q5RDJFMDExQkI3QkRGOUNFMzAzQThBQSIgeG1wTU06RG9jdW1lbnRJRD0ieG1wLmRpZDozRUM2QzdERTVGREQxMUUyQkM2MDk5QzBCRTQyNjExQiIgeG1wTU06SW5zdGFuY2VJRD0ieG1wLmlpZDozRUM2QzdERDVGREQxMUUyQkM2MDk5QzBCRTQyNjExQiIgeG1wOkNyZWF0b3JUb29sPSJBZG9iZSBQaG90b3Nob3AgQ1M1IFdpbmRvd3MiPiA8eG1wTU06RGVyaXZlZEZyb20gc3RSZWY6aW5zdGFuY2VJRD0ieG1wLmlpZDo1OUVDNTc3RkQzNUZFMjExQjZCMkMzMkRFRjFGMDVEQSIgc3RSZWY6ZG9jdW1lbnRJRD0ieG1wLmRpZDpDRTUxMjNGN0Q5RDJFMDExQkI3QkRGOUNFMzAzQThBQSIvPiA8L3JkZjpEZXNjcmlwdGlvbj4gPC9yZGY6UkRGPiA8L3g6eG1wbWV0YT4gPD94cGFja2V0IGVuZD0iciI/Pi1y+AYAAAJrSURBVHjaxJfNbtNAEIBnY7tGUaASqsslEtwrJA6ccuAGZx6gL8E7IV6oUgWnXEJcKZBWTvy7O7PM2kljB2pb0ZKMNI6UZDzfzp/HQmsNp5QBnFjcyWTijMdjPwgCx/d9GAz+LxMRQZ7nsFgscDab5W4URS/effm8vBiewzPHg4EQDQOToO0311cfezmJvn5rIdCgswzw/h4+3N6+dKfT6Xm4XsLVxWvwnbMKQDxB0FOcy6AVgPIM5M85GN9ukiR+uP4Nc9YcJfuqvIma/618evO+F4D8/qOy3RS44EM9FjsDgO+BDOdgfLulASIskxWsVGolz2p+1/6H5yPAQlZFaC6ICjJVlGql0DjHreK5oKXaASiNkKgMUplbAdBp0lEkAghrAEgIkUwZwg4ArTsAiDUvdgCSAeIihRTtpEAn7QBaE+iiaEZgxREwXWAlAnGy18PNXtYKQdcjoBhgnadQkHpswW37iUMAnoqAaUXTklIyRB0ACZKChwMXY0PE3iDonYK4/XfPA70Z+bsuKGIGICspwIeH9ggxAIxGtSLkQYRmRJrj7o/Ag3Kg/zFH64QIpGS9BiSQILajv20OWReoPZLCPJAkNmtAOwbc0nLSAWCKUctGF3D1O441AN0BYB5MSjUigOCdORxtSxHoOgi3IqraKDZbivFtbT/scR8i3O2ExBEQAo4mZj+gTZrKCGguQsByJrcvGrLfqFYdqRSlq30ARTDUXqthHMe9ALLhsBOg2MwKt4Thnox+LTt7PgzDXgB3UdQJ4FQTDs31Fetb1uDIrwQL1hsD4JstbfN5TDHbz0qc+tXsjwADALHablodmXivAAAAAElFTkSuQmCC",
    sets: ["all"],
    all: ["\\","1","2","3","4","5","6","7","8","9","0","\'","ì","backspace","EOL",
        "tab","q","w","e","r","t","y","u","i","o","p","è","+","return","EOL",
        "{capslock}","a","s","d","f","g","h","j","k","l","ò","à","ù","EOL",
        "[shift]","<","z","x","c","v","b","n","m",",",".","-","[rightshift]","EOL",
        "selector","[alt]","space","[alt]","EOL"],
    all_shift: ["|","!","'","£","$","%","&","/","(",")","=","?","^","backspace","EOL",
        "tab","Q","W","E","R","T","Y","U","I","O","P","é","*","return","EOL",
        "{capslock}","A","S","D","F","G","H","J","K","L","ç","°","§","EOL",
        "[shift]",">","Z","X","C","V","B","N","M",";",":","_","[rightshift]","EOL",
        "selector","[alt]","space","[alt]","EOL"],
    all_capslock: ["\\","1","2","3","4","5","6","7","8","9","0","\'","ì","backspace","EOL",
        "tab","Q","W","E","R","T","Y","U","I","O","P","é","*","return","EOL",
        "{capslock}","A","S","D","F","G","H","J","K","L","ç","°","§","EOL",
        "[shift]","<","Z","X","C","V","B","N","M",",",".","-","[rightshift]","EOL",
        "selector","[alt]","space","[alt]","EOL"],
    all_alt: ["@","«","“","‘","{","Ç","¶","}","∞","`","´","–","≠","backspace","EOL",
        "tab","⁄","Ω","™","®","†","¥","¨","€","ø","π","œ","¢","return","EOL",
        "{capslock}","å","ß","∂","ƒ","Ÿ","∆","ª","º","¬","µ","æ","@","EOL",
        "[shift]","≤","∑","≈","©","√","∫","~","¿","…","|","¡","[rightshift]","EOL",
        "selector","[alt]","space","[alt]","EOL"],
    all_alt_shift: ["#","»","”","’","[","Ì","•","]","","Ô","Ò","—","±","backspace","EOL",
        "tab","Á","Ë","È","Í","Ï","Î","Û","Ù","Ø","∏","Œ","Ú","return","EOL",
        "{capslock}","Å","ﬁ","ﬂ","‡","‚","·","ˆ","˜","ı","¯","Æ","#","EOL",
        "[shift]","≥","„","‰","Â","◊","Ê","˙","˚","÷","\\","˘","[rightshift]","EOL",
        "selector","[alt]","space","[alt]","EOL"],
    all_alt_capslock: ["@","«","“","‘","{","Ç","¶","}","∞","`","´","–","≠","backspace","EOL",
        "tab","Á","Ë","È","Í","Ï","Î","Û","Ù","Ø","∏","Œ","Ú","return","EOL",
        "{capslock}","Å","ﬁ","ﬂ","‡","‚","·","ˆ","˜","ı","¯","Æ","#","EOL",
        "[shift]","≥","„","‰","Â","◊","Ê","˙","˚","÷","\\","˘","[rightshift]","EOL",
        "selector","[alt]","space","[alt]","EOL"],
    "all_^": ["empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "backspace", "EOL",
        "tab", "empty", "empty", "ê", "empty", "empty", "empty", "û", "î", "ô", "empty", "[^]", "empty", "return", "EOL",
        "{capslock}", "â", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "EOL",
        "[shift]", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "[rightshift]", "EOL",
        "selector", "[alt]", "space", "[alt]", "EOL"],
    "all_^_shift": ["empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "backspace", "EOL",
        "tab", "empty", "empty", "Ê", "empty", "empty", "empty", "Û", "Î", "Ô", "empty", "[^]", "empty", "return", "EOL",
        "{capslock}", "Â", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "EOL",
        "[shift]", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "[rightshift]", "EOL",
        "selector", "[alt]", "space", "[alt]", "EOL"],
    "all_alt_^": ["all_^"],
    "all_^_alt": ["all_^"],    
    "all_alt_^_shift": ["all_^_shift"],
    "all_^_alt_shift": ["all_^_shift"],    
    "all_alt_^_capslock": ["all_^_shift"],
    "all_^_alt_capslock": ["all_^_shift"],    
    "all_shift_^": ["all_^_shift"],
    "all_capslock_^": ["all_^_shift"],
    "all_^_capslock": ["all_^_shift"],        
    all_shift_capslock: ["all_shift"],
    all_capslock_shift: ["all_shift"],
    all_shift_alt: ["all_alt_shift"],
    all_capslock_alt: ["all_alt_capslock"],
    all_alt_capslock_shift: ["all_alt_shift"],
    all_alt_shift_capslock: ["all_alt_shift"],
    all_shift_alt_capslock: ["all_alt_shift"],
    all_capslock_alt_shift: ["all_alt_shift"],
    all_capslock_shift_alt: ["all_alt_shift"],
    all_shift_capslock_alt: ["all_alt_shift"]
};

layouts["ja"] = {
    name: "日本語配列",
    icon: "iVBORw0KGgoAAAANSUhEUgAAACAAAAAcCAMAAAA3HE0QAAAAwFBMVEX////19vgAAAAAAADg4eMAAADm5uhKSkutrrBtbm9YWVqWlpeAgYKOjpBZWVqHh4mIiYuJiotWVlhWV1iBgYOGh4mGhojZ2t3a297f4OPj5Ofk5ejm5+nq6+7s7fDt7vHw8fTy8/bz3uHz3+Lz4OPz9Pf09ff19vj2o6X2pKb29vn29/n3+Pr4c3X4dnj4d3n4+Pr8Kir8Kyv8LCz8LS38Ly/9Cgv9Cwz9DA39DQ79Dg7+AAD+AQH+BQX+Bgb+BwdoW9a8AAAAF3RSTlMAAwQKCw4OFhgwMzRAQkNDQ0NERHSQked/HzUAAADISURBVHjapdFrE0JQEIDhjQohpPsFSUR3XXWU//+vmjEmmjnLTD2f35mzZxf+V6s3S9RrwAebA2oT8CC63hrluSLI1tJFLS0ZNNOaoyxTA83IA2cbJsl57+SB8RX4D5KKfHrgxyQT+7RgEZGPyKYEe1KwpQTnYhBSgqQYvKqCW9UTp1+GtPFvVi8qs7qT1J226uxYx+f1ssOOlfsK1JlhooyZCsp0MkZNpgpIo+EANRxJIHR7fVSvKwDXausdhN5uccCwjRIs8wYdcm3kooAHgAAAAABJRU5ErkJggg==",
    sets : ["all"],
    all: ["1","2","3","4","5","6","7","8","9","0","-","^","¥","backspace","EOL",
        "tab","q","w","e","r","t","y","u","i","o","p","@","[","return","EOL",
        "{capslock}","a","s","d","f","g","h","j","k","l",";",":","]","EOL",
        "[shift]","z","x","c","v","b","n","m",",",".","/","_","[rightshift]","EOL",
        "selector","[alt]","space","[alt]","EOL"],
    all_shift: ["!","'","#","$","%","&","\'","(",")","0","=","~","|","backspace","EOL",
        "tab","Q","W","E","R","T","Y","U","I","O","P","`","{","return","EOL",
        "{capslock}","A","S","D","F","G","H","J","K","L","+","*","}","EOL",
        "[shift]","Z","X","C","V","B","N","M","<",">","?","_","[rightshift]","EOL",
        "selector","[alt]","space","[alt]","EOL"],
    all_capslock: ["1","2","3","4","5","6","7","8","9","0","-","^","¥","backspace","EOL",
        "tab","Q","W","E","R","T","Y","U","I","O","P","`","{","return","EOL",
        "{capslock}","A","S","D","F","G","H","J","K","L","+","*","}","EOL",
        "[shift]","Z","X","C","V","B","N","M","<",">","?","~","[rightshift]","EOL",
        "selector","[alt]","space","[alt]","EOL"],
    all_alt: ["¡","™","£","¢","∞","§","¶","•","ª","º","–","≠","¥","backspace","EOL",
        "tab","œ","∑","´","®","†","¥","¨","ˆ","ø","π","“","‘","return","EOL",
        "{capslock}","å","ß","∂","ƒ","©","˙","∆","˚","¬","…","æ","«","EOL",
        "[shift]","Ω","≈","ç","√","∫","˜","µ","≤","≥","÷","`","[rightshift]","EOL",
        "selector","[alt]","space","[alt]","EOL"],
    all_alt_shift: ["⁄","€","‹","›","ﬁ","ﬂ","‡","°","·","‚","—","±","|","backspace","EOL",
        "tab","Œ","„","´","‰","˛","Á","¨","ˆ","Ø","∏","”","’","return","EOL",
        "{capslock}","Å","Í","Î","Ï","˝","Ó","Ô","","Ò","Ú","Æ","»","EOL",
        "[shift]","¸","˛","Ç","◊","ı","˜","Â","¯","˘","¿","`","[rightshift]","EOL",
        "selector","[alt]","space","[alt]","EOL"],
    all_capslock_alt: ["1","2","3","4","5","6","7","8","9","0","-","^","§","backspace","EOL",
        "tab","Œ","„","´","‰","˛","Á","¨","ˆ","Ø","∏","”","’","return","EOL",
        "{capslock}","Å","Í","Î","Ï","˝","Ó","Ô","","Ò","Ú","Æ","»","EOL",
        "[shift]","¸","˛","Ç","◊","ı","˜","Â","¯","˘","¿","`","[rightshift]","EOL",
        "selector","[alt]","space","[alt]","EOL"],
    all_shift_alt: ["all_alt_shift"],
    all_alt_capslock: ["all_capslock_alt"],
    all_alt_capslock_shift: ["all_alt"],
    all_alt_shift_capslock: ["all_alt"],
    all_shift_alt_capslock: ["all_alt"],
    all_capslock_alt_shift: ["all_alt"],
    all_capslock_shift_alt: ["all_alt"],
    all_shift_capslock_alt: ["all_alt"]
};

layouts["kk"] = {
    name: "Қазақ",
    icon: "iVBORw0KGgoAAAANSUhEUgAAACAAAAAcCAYAAAAAwr0iAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAA3BpVFh0WE1MOmNvbS5hZG9iZS54bXAAAAAAADw/eHBhY2tldCBiZWdpbj0i77u/IiBpZD0iVzVNME1wQ2VoaUh6cmVTek5UY3prYzlkIj8+IDx4OnhtcG1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iIHg6eG1wdGs9IkFkb2JlIFhNUCBDb3JlIDUuNi1jMTExIDc5LjE1ODMyNSwgMjAxNS8wOS8xMC0wMToxMDoyMCAgICAgICAgIj4gPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4gPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIgeG1sbnM6eG1wTU09Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9tbS8iIHhtbG5zOnN0UmVmPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvc1R5cGUvUmVzb3VyY2VSZWYjIiB4bWxuczp4bXA9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC8iIHhtcE1NOk9yaWdpbmFsRG9jdW1lbnRJRD0ieG1wLmRpZDpDRTUxMjNGN0Q5RDJFMDExQkI3QkRGOUNFMzAzQThBQSIgeG1wTU06RG9jdW1lbnRJRD0ieG1wLmRpZDpDRkM2MzA3MDI2QjAxMUU2QTYyN0Q0NThCRDY2RTM4RiIgeG1wTU06SW5zdGFuY2VJRD0ieG1wLmlpZDo4RTI0Mzc3QTI2QjAxMUU2QTYyN0Q0NThCRDY2RTM4RiIgeG1wOkNyZWF0b3JUb29sPSJBZG9iZSBQaG90b3Nob3AgQ0MgMjAxNSAoTWFjaW50b3NoKSI+IDx4bXBNTTpEZXJpdmVkRnJvbSBzdFJlZjppbnN0YW5jZUlEPSJ4bXAuaWlkOmRmMjRmMGE3LTUyYzItNDcxYi1iNGVhLTVkNjQ2MjNmNjA4ZCIgc3RSZWY6ZG9jdW1lbnRJRD0ieG1wLmRpZDpDRTUxMjNGN0Q5RDJFMDExQkI3QkRGOUNFMzAzQThBQSIvPiA8L3JkZjpEZXNjcmlwdGlvbj4gPC9yZGY6UkRGPiA8L3g6eG1wbWV0YT4gPD94cGFja2V0IGVuZD0iciI/PsTc9EQAAALiSURBVHja7JfPaxNBFMe/s7vZTdI2La0VNaVisShSvGhFxV4EBUXwIPSknkSliCdvIv4RHjwJ4lFR0Ev1UMWLFkWwRcUftSq2Km3TH0nzY3/MjG+mELUklg1uc/FBkk32Le8z733fmwmTUqKeZqDOVncAS731P3wu2+MOEpYJFnFAVfBiwDFdcnFzfy/TABP5EoTtICUZTBYtAifNZQXwjWKWM5AhGnexgOYYVYQZRBkdhKAU5PwAeYpZBpCcoxvvcNIexI3iYYz43dHWQQgd8w8RxlgAn3hiCFZfhMp8aSGJEjxCWMmaWAFd1iS6zEk4zMcbfxM+8/XIyobaAYpwMCNaUJL2isEPOsNoNvLYYMxAkF7icLHF+oIH7u7QEGWANiOLJCuhjWX/+oBaeYogziVvIcGWhKSgrxT60W19xQt/a22DSC77rGSM7vZYH5E2p8vBlcWZh7QxjW3WJ+1TE8CcaEJBxjErUxUdN5rfdYaqlUgF9mQMDeTTYU6FB3CoB1qpDGo1lWwgeRsHnGf4wDsxyduxKBPle+p6QqzFGO/A0fhjnEreDa8BhwJ79FWBVDKTCRxynuJC9rxW/9XCMdLLAgwmSbzNmKcMjvM0LjVew6tgc3gAl1Jr0wxwq7ThoLuH6j+OffYIhtxenWYlOjU3Xgdd+CFaNeCQtwtjQUf4EqjAsyKl61jJHrk70W7M6TG91x5FI3WCart7pT7qoAX0xUaQJw2ljSn9e2iAFmNRl6GF5SpPTwp8OXca87KRVtumBXsmeQc7Ym/1/MiQePOkhYu5s9o3dAnUFmSu8Cgnr2GvR1+rLCQI+HjiPsHn8D7oxPXiEfIxaxtEGUq/WlWmShsutyfedv36ZyeiBKlgjTFftQ0jP5Kp3bBAU92u0obR7oaCw+OGbimP00zzI4ZQJ3HBfzuQUMCX2XUYXThBJxY1VPMR5/3XIpcAAh+B565q6pmxVH32/49JvQF+CjAAPrUtGDLAeowAAAAASUVORK5CYII=",
    sets: ["all"],
    all: ["(","'","ә","і","ң","ғ",",",".","ү","ұ","қ","ө","һ","backspace","EOL",
        "tab","й","ц","у","к","е","н","г","ш","щ","з","х","ъ","return","EOL",
        "{capslock}","ф","ы","в","а","п","р","о","л","д","ж","э","ё","EOL",
        "[shift]","]","я","ч","с","м","и","т","ь","б","ю","/","[rightshift]","EOL",
        "selector","[alt]","space","[alt]","EOL"],
    all_alt: ["§","1","2","3","4","5","6","7","8","9","0","-","=","backspace","EOL",
        "tab","ј","џ","ў","ќ","†","њ","ѓ","ѕ","\'","‘","“","ґ","return","EOL",
        "{capslock}","ƒ","ы","ћ","÷","©","}","°","љ","∆","…","є","\\","EOL",
        "[shift]","`","ђ","≈","≠","µ","и","™","~","≤","≥","ї","[rightshift]","EOL",
        "selector","[alt]","space","[alt]","EOL"],
    all_shift: [")","!","Ә","І","Ң","Ғ",";",":","Ү","Ұ","Қ","Ө","Һ","backspace","EOL",
        "tab","Й","Ц","У","К","Е","Н","Г","Ш","Щ","З","Х","Ъ","return","EOL",
        "{capslock}","Ф","Ы","В","А","П","Р","О","Л","Д","Ж","Э","Ё","EOL",
        "[shift]","[","Я","Ч","С","М","И","Т","Ь","Б","Ю","?","[rightshift]","EOL",
        "selector","[alt]","space","[alt]","EOL"],
    all_capslock: [">","'","Ә","І","Ң","Ғ",",",".","Ү","Ұ","Қ","Ө","Һ","backspace","EOL",
        "tab","Й","Ц","У","К","Е","Н","Г","Ш","Щ","З","Х","Ъ","return","EOL",
        "{capslock}","Ф","Ы","В","А","П","Р","О","Л","Д","Ж","Э","Ё","EOL",
        "[shift]","]","Я","Ч","С","М","И","Т","Ь","Б","Ю","/","[rightshift]","EOL",
        "selector","[alt]","space","[alt]","EOL"],
    all_alt_capslock: ["±","!","@","#","$","€","^","&","*","(",")","_","+","backspace","EOL",
        "tab","Ј","Џ","Ў","Ќ","†","Њ","Ѓ","Ѕ","„","’","”","Ґ","return","EOL",
        "{capslock}","ƒ","Ы","Ћ","÷","©","{","•","Љ","∆","…","Є","|","EOL",
        "[shift]","~","Ђ","≈","≠","µ","И","™","~","<",">","Ї","[rightshift]","EOL",
        "selector","[alt]","space","[alt]","EOL"],
    all_alt_shift: ["±","!","@","#","$","€","^","&","*","(",")","_","+","backspace","EOL",
        "tab","Ј","Џ","Ў","Ќ","†","Њ","Ѓ","Ѕ","„","’","”","Ґ","return","EOL",
        "{capslock}","ƒ","Ы","Ћ","÷","©","{","•","Љ","∆","…","Є","|","EOL",
        "[shift]","~","Ђ","≈","≠","µ","И","™","~","<",">","Ї","[rightshift]","EOL",
        "selector","[alt]","space","[alt]","EOL"],
    all_shift_capslock: ["all_shift"],
    all_capslock_shift: ["all_shift"],
    all_shift_alt: ["all_alt_shift"],
    all_capslock_alt: ["all_alt_capslock"],
    all_alt_capslock_shift: ["all_alt_shift"],
    all_alt_shift_capslock: ["all_alt_shift"],
    all_shift_alt_capslock: ["all_alt_shift"],
    all_capslock_alt_shift: ["all_alt_shift"],
    all_capslock_shift_alt: ["all_alt_shift"],
    all_shift_capslock_alt: ["all_alt_shift"]
};

layouts["pl"] = {
    name: "Polski",
    icon: "iVBORw0KGgoAAAANSUhEUgAAACAAAAAcCAYAAAAAwr0iAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAA2RpVFh0WE1MOmNvbS5hZG9iZS54bXAAAAAAADw/eHBhY2tldCBiZWdpbj0i77u/IiBpZD0iVzVNME1wQ2VoaUh6cmVTek5UY3prYzlkIj8+IDx4OnhtcG1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iIHg6eG1wdGs9IkFkb2JlIFhNUCBDb3JlIDUuMC1jMDYwIDYxLjEzNDc3NywgMjAxMC8wMi8xMi0xNzozMjowMCAgICAgICAgIj4gPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4gPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIgeG1sbnM6eG1wTU09Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9tbS8iIHhtbG5zOnN0UmVmPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvc1R5cGUvUmVzb3VyY2VSZWYjIiB4bWxuczp4bXA9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC8iIHhtcE1NOk9yaWdpbmFsRG9jdW1lbnRJRD0ieG1wLmRpZDpDRTUxMjNGN0Q5RDJFMDExQkI3QkRGOUNFMzAzQThBQSIgeG1wTU06RG9jdW1lbnRJRD0ieG1wLmRpZDozRUEzMTI1QjVGREQxMUUyQkM2MDk5QzBCRTQyNjExQiIgeG1wTU06SW5zdGFuY2VJRD0ieG1wLmlpZDozRUEzMTI1QTVGREQxMUUyQkM2MDk5QzBCRTQyNjExQiIgeG1wOkNyZWF0b3JUb29sPSJBZG9iZSBQaG90b3Nob3AgQ1M1IFdpbmRvd3MiPiA8eG1wTU06RGVyaXZlZEZyb20gc3RSZWY6aW5zdGFuY2VJRD0ieG1wLmlpZDo1OUVDNTc3RkQzNUZFMjExQjZCMkMzMkRFRjFGMDVEQSIgc3RSZWY6ZG9jdW1lbnRJRD0ieG1wLmRpZDpDRTUxMjNGN0Q5RDJFMDExQkI3QkRGOUNFMzAzQThBQSIvPiA8L3JkZjpEZXNjcmlwdGlvbj4gPC9yZGY6UkRGPiA8L3g6eG1wbWV0YT4gPD94cGFja2V0IGVuZD0iciI/PraMmXQAAAFHSURBVHja7JcxT4VADMd7B+QS8A0OxIVBZ2LiZsL3/wZ+ABcGEzYVnufRO1sEIQzPvER7y2tSSCHk/7vetQ0qhAAxTUNkS5umSaqqMmVZJsYY0Pp/mbz3YK2FruuwbVsLdV1fh0jG2irP89u+759jpL8oijs9DIPhtEgba7L2tOGICJIQrMWaP1UQoxQXzehleAG4AMSfBXxpHx4BhiNo52T6QJYBHK5WAD+OoLkxSDUjbnxuXAECAajgxQBYK4xuBUACSLkzSWWAtLzbAHA6goLzAfibsIthfrZ/t2vDuN0CjxSk2UR23kpOxOE0OeIWYFm54FBaNL/HMQdKyRU/aS0AUwZGT4fit6z9pT5r4gbAUVl8MECeiwF8hhUALa395f1V7AjwbidzS2KYG/J78lJ4DHTkTwxgyA/zXdIs+ZuK/Wv2JcAAKUQeDX3mvq8AAAAASUVORK5CYII=",
    sets: ["all"],
    all: ["§", "1", "2", "3", "4", "5", "6", "7", "8", "9", "0", "-", "=", "backspace", "EOL",
        "tab", "q", "w", "e", "r", "t", "y", "u", "i", "o", "p", "[", "]", "return", "EOL",
        "{capslock}", "a", "s", "d", "f", "g", "h", "j", "k", "l", ";", "\'", "\\", "EOL",
        "[shift]", "`", "z", "x", "c", "v", "b", "n", "m", ",", ".", "/", "[rightshift]", "EOL",
        "selector", "[alt]", "space", "[alt]", "EOL"],
    all_shift: ["£", "!", "@", "#", "$", "%", "^", "&", "*", "(", ")", "_", "+", "backspace", "EOL",
        "tab", "Q", "W", "E", "R", "T", "Z", "U", "I", "O", "P", "{", "}", "return", "EOL",
        "{capslock}", "A", "S", "D", "F", "G", "H", "J", "K", "L", ":", "'", "|", "EOL",
        "[shift]", "~", "Z", "X", "C", "V", "B", "N", "M", "<", ">", "?", "[rightshift]", "EOL",
        "selector", "[alt]", "space", "[alt]", "EOL"],
    all_capslock: ["£", "1", "2", "3", "4", "5", "6", "7", "8", "9", "0", "-", "=", "backspace", "EOL",
        "tab", "Q", "W", "E", "R", "T", "Y", "U", "I", "O", "P", "[", "]", "return", "EOL",
        "{capslock}", "A", "S", "D", "F", "G", "H", "J", "K", "L", ";", "\'", "\\", "EOL",
        "[shift]", "`", "Z", "X", "C", "V", "B", "N", "M", ",", ".", "/", "[rightshift]", "EOL",
        "selector", "[alt]", "space", "[alt]", "EOL"],
    all_alt: ["¬", "Ń", "™", "€", "ß", "į", "§", "¶", "•", "Ľ", "ľ", "–", "≠", "backspace", "EOL",
        "tab", "Ō", "∑", "ę", "®", "†", "ī", "¨", "^", "ó", "Ļ", "„", "‚", "return", "EOL",
        "{capslock}", "ą", "ś", "∂", "ń", "©", "ķ", "∆", "Ż", "ł", "…", "ĺ", "«", "EOL",
        "[shift]", "`", "ż", "ź", "ć", "√", "ļ", "ń", "Ķ", "≤", "≥", "÷", "[rightshift]", "EOL",
        "selector", "[alt]", "space", "[alt]", "EOL"],
    all_alt_shift: ["¬", "ŕ", "Ř", "‹", "›", "ř", "Ŗ", "ŗ", "°", "Š", "‚", "—", "Ī", "backspace", "EOL",
        "tab", "ő", "„", "Ę", "£", "ś", "Á", "Ť", "ť", "Ó", "ł", "”", "’", "return", "EOL",
        "{capslock}", "Ą", "Ś", "Ž", "ž", "Ū", "Ó", "Ô", "ū", "Ł", "Ú", "ģ", "»", "EOL",
        "[shift]", "Ŕ", "Ż", "Ź", "Ć", "◊", "ű", "Ń", "ų", "Ý", "ý", "ņ", "[rightshift]", "EOL",
        "selector", "[alt]", "space", "[alt]", "EOL"],
    all_alt_capslock: ["¬", "Ń", "™", "£", "Ę", "į", "§", "¶", "•", "Ľ", "ľ", "–", "≠", "backspace", "EOL",
        "tab", "ő", "„", "Ę", "Ś", "ś", "Á", "Ť", "ť", "Ó", "ł", "”", "’", "return", "EOL",
        "{capslock}", "Ą", "Ś", "Ž", "ž", "Ū", "Ó", "Ô", "ū", "Ł", "…", "ģ", "«", "EOL",
        "[shift]", "`", "Ż", "Ź", "Ć", "◊", "ű", "Ń", "ų", "≤", "≥", "÷", "[rightshift]", "EOL",
        "selector", "[alt]", "space", "[alt]", "EOL"],
    all_shift_alt: ["all_alt_shift"],
    all_capslock_alt: ["all_alt_capslock"],
    all_shift_capslock: ["all_shift"],
    all_capslock_shift: ["all_shift"],
    all_alt_capslock_shift: ["all_alt_shift"],
    all_alt_shift_capslock: ["all_alt_shift"],
    all_shift_alt_capslock: ["all_alt_shift"],
    all_capslock_alt_shift: ["all_alt_shift"],
    all_capslock_shift_alt: ["all_alt_shift"],
    all_shift_capslock_alt: ["all_alt_shift"]
};

layouts["pt"] = {"name": "Português",
    icon: "iVBORw0KGgoAAAANSUhEUgAAACAAAAAcCAYAAAAAwr0iAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAA2RpVFh0WE1MOmNvbS5hZG9iZS54bXAAAAAAADw/eHBhY2tldCBiZWdpbj0i77u/IiBpZD0iVzVNME1wQ2VoaUh6cmVTek5UY3prYzlkIj8+IDx4OnhtcG1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iIHg6eG1wdGs9IkFkb2JlIFhNUCBDb3JlIDUuMC1jMDYwIDYxLjEzNDc3NywgMjAxMC8wMi8xMi0xNzozMjowMCAgICAgICAgIj4gPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4gPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIgeG1sbnM6eG1wTU09Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9tbS8iIHhtbG5zOnN0UmVmPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvc1R5cGUvUmVzb3VyY2VSZWYjIiB4bWxuczp4bXA9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC8iIHhtcE1NOk9yaWdpbmFsRG9jdW1lbnRJRD0ieG1wLmRpZDpDRTUxMjNGN0Q5RDJFMDExQkI3QkRGOUNFMzAzQThBQSIgeG1wTU06RG9jdW1lbnRJRD0ieG1wLmRpZDozRUEzMTI1NzVGREQxMUUyQkM2MDk5QzBCRTQyNjExQiIgeG1wTU06SW5zdGFuY2VJRD0ieG1wLmlpZDozRUEzMTI1NjVGREQxMUUyQkM2MDk5QzBCRTQyNjExQiIgeG1wOkNyZWF0b3JUb29sPSJBZG9iZSBQaG90b3Nob3AgQ1M1IFdpbmRvd3MiPiA8eG1wTU06RGVyaXZlZEZyb20gc3RSZWY6aW5zdGFuY2VJRD0ieG1wLmlpZDo1OUVDNTc3RkQzNUZFMjExQjZCMkMzMkRFRjFGMDVEQSIgc3RSZWY6ZG9jdW1lbnRJRD0ieG1wLmRpZDpDRTUxMjNGN0Q5RDJFMDExQkI3QkRGOUNFMzAzQThBQSIvPiA8L3JkZjpEZXNjcmlwdGlvbj4gPC9yZGY6UkRGPiA8L3g6eG1wbWV0YT4gPD94cGFja2V0IGVuZD0iciI/Ppj36JgAAAQLSURBVHjaxFdNbBtFFP5m1+uN7WzsuDGpigutoFRACXBArVIBEhLiR6qoxKU9caFXJA7ce+KExAVxRqggOCFx4QJCSqFCKlIlEAm0EIfUdhw5sR2vvev9mR3eOHa8Tt1mW4tkpOdZr2bnffu97703y4QQOMih4IBHbH5+Xs3n83oul1N1XYei/L+YgiCA4zioVqu8WCw6sWazOXXq/bdquWQaE2ocjLE9N3n7+vqDIxABgk4HQa2OFxcXs7FCoZAutzdxKneMAGhQIgBQD4+hm0BAIQBOqQTpO2ZZll42N1Eic7kH9Pyz3oXAsDN5/8wfxf4fYBSW/jsI3LmOGGBxHV6pAuk7Ju/xgKNmNWH6dqSX4Gtr4wnBMOB77rYI5Y/Pfdi+07VILNr2mNKPIXC9EABSpsUlAPeez+U0G3lmwnzcRKKsQN18wIxRVXLqhwAIDtO1YN2FAUN18fpMCX86acQmbOjGFpxUHPykj8Q1DWqb3WcmkLLccAgCHy23A5vfyUCKdfCesYybC7OYKwZQMpTDdR2HbutYbSvIXmgg/ZmPWJPdRyYGoGIwAMB5ANOz4QTeQL1MAhW4/OR1TLcSOFJewhNrR1HJKuA5KlhV2kRfAV+eRO1iFTMfT5E4QhkQ2mdn7t/2OURYhF6XgQEAmWoy/QzVg+80STDA9HcBZn78EEuNFDEm8OwlG1uvXYB62oG36sKPt6DWlD2pp0pHzj0Enj8sQgnAIy2ER17UsGF28NPKUcy9cQu3f/0HjalHuuu/Xymi/eomHktMQzzfQLuYgEFhiRQCV6MuxEIMkGPLadMcDC2sig7aXhMVq4OLXzn496yKCjn3uECyo+LE1y7W32xAlOpI1lzwRjxaGmsEwJgcdEOfcypGgqrksBXdJFpCRzmtofCwikzjG+Rns3j08CE8tPEt/j7OkD9vQyMBphZV2WmiGfnbFQIPglGT2MWALRh+q0/hUv4qFt45g3Off4HnPrkBV1OwPHkTyrtZ2E//hcy1FJS2uEtdHlGpyY/wvTADQVcfuxmQ9mX9BAr2NDLHl3D53FlceSmFRqaNuEgjvVpA/YoO9ulE9LeXJvf2QpXQo1LMqDrJtNvdP+T8QeEFvJIu4fRTN+DNUcXM1zGxoUD5OYHEL5qM6vZzbET6jUwGAR4OgWxGMab2txlqZP35h60jWLIzOMnW8fKCBeNWHOq6MuxFYPT1iHbJeQhA0KVlG9m9RslJoIRj+OhqOYqXPU9GOxoISJWMYf8GOesD2GaA8hq8G4tIz/vj+u8JfweAIAaoHiMptEgbdJLJsQG4YgCAUxqgtVGPHNGK2Rw3AlB7hysJZpbsGXne2OdPgirZ7xKA7CBGb97PIQ8EJjvoT7P/BBgARdtOFmcozyEAAAAASUVORK5CYII=",
    sets: ["all"],
    all: ["§","1","2","3","4","5","6","7","8","9","0","\'","+","backspace","EOL",
        "tab","q","w","e","r","t","y","u","i","o","p","º","[´]","return","EOL",
        "{capslock}","a","s","d","f","g","h","j","k","l","ç","[~]","\\","EOL",
        "[shift]","<","z","x","c","v","b","n","m",",",".","-","[rightshift]","EOL",
        "selector","[alt]","space","[alt]","EOL"],
    all_shift: ["±","!","'","#","$","%","&","/","(",")","=","?","*","backspace","EOL",
        "tab","Q","W","E","R","T","Y","U","I","O","P","ª","`","return","EOL",
        "{capslock}","A","S","D","F","G","H","J","K","L","Ç","^","|","EOL",
        "[shift]",">","Z","X","C","V","B","N","M",";",":","_","[rightshift]","EOL",
        "selector","[alt]","space","[alt]","EOL"],
    all_capslock: ["§","1","2","3","4","5","6","7","8","9","0","\'","+","backspace","EOL",
        "tab","Q","W","E","R","T","Y","U","I","O","P","ª","`","return","EOL",
        "{capslock}","A","S","D","F","G","H","J","K","L","Ç","^","|","EOL",
        "[shift]",">","Z","X","C","V","B","N","M",";",":","_","[rightshift]","EOL",
        "selector","[alt]","space","[alt]","EOL"],
    all_alt: ["§","","@","€","£","‰","¶","÷","[","]","≠","§","±","backspace","EOL",
        "tab","œ","∑","æ","®","™","¥","†","ı","ø","π","°","¨","return","EOL",
        "{capslock}","å","ß","∂","ƒ","˙","ˇ","¯","„","‘","¸","˜","‹","EOL",
        "[shift]","≤","Ω","«","©","√","∫","¬","µ","“","…","—","[rightshift]","EOL",
        "selector","[alt]","space","[alt]","EOL"],
    all_alt_shift: ["±","¡","ﬁ","ﬂ","¢","∞","•","⁄","{","}","≈","¿","◊","backspace","EOL",
        "tab","Œ","∑","Æ","®","™","¥","‡","˚","Ø","∏","˚","˝","return","EOL",
        "{capslock}","Å","ß","∆","ƒ","˙","ˇ","¯","‚","’","˛","ˆ","›","EOL",
        "[shift]","≥","Ω","»","©","√","∫","¬","µ","”","·","–","[rightshift]","EOL",
        "selector","[alt]","space","[alt]","EOL"],
    all_alt_capslock: ["§","","@","€","£","‰","¶","÷","[","]","≠","§","±","backspace","EOL",
        "tab","Œ","∑","Æ","®","™","¥","‡","˚","Ø","∏","˚","˝","return","EOL",
        "{capslock}","Å","ß","∆","ƒ","˙","ˇ","¯","‚","’","˛","ˆ","›","EOL",
        "[shift]","≥","Ω","»","©","√","∫","¬","µ","”","·","–","[rightshift]","EOL",
        "selector","[alt]","space","[alt]","EOL"],
    "all_~": ["empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "backspace", "EOL",
        "tab", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "õ", "empty", "empty", "empty", "return", "EOL",
        "{capslock}", "ã", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "[~]", "empty", "EOL",
        "[shift]", "empty", "empty", "empty", "empty", "empty", "empty", "ñ", "empty", "empty", "empty", "empty", "[rightshift]", "EOL",
        "selector", "[alt]", "space", "[alt]", "EOL"],    
    "all_~_shift": ["empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "backspace", "EOL",
        "tab", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "Õ", "empty", "empty", "empty", "return", "EOL",
        "{capslock}", "Ã", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "[~]", "empty", "EOL",
        "[shift]", "empty", "empty", "empty", "empty", "empty", "empty", "Ñ", "empty", "empty", "empty", "empty", "[rightshift]", "EOL",
        "selector", "[alt]", "space", "[alt]", "EOL"],    
    "all_´": ["empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "backspace", "EOL",
        "tab", "empty", "empty", "é", "empty", "empty", "empty", "ú", "í", "ó", "empty", "empty", "[´]", "return", "EOL",
        "{capslock}", "á", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "EOL",
        "[shift]", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "[rightshift]", "EOL",
        "selector", "[alt]", "space", "[alt]", "EOL"],    
    "all_´_shift": ["empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "backspace", "EOL",
        "tab", "empty", "empty", "È", "empty", "empty", "empty", "Ù", "Ì", "Ò", "empty", "empty", "[´]", "return", "EOL",
        "{capslock}", "À", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "EOL",
        "[shift]", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "[rightshift]", "EOL",
        "selector", "[alt]", "space", "[alt]", "EOL"],            
    "all_shift_~": ["all_~_shift"],
    "all_capslock_~": ["all_~_shift"],
    "all_~_capslock": ["all_~_shift"],    
    "all_shift_´": ["all_´_shift"],
    "all_capslock_´": ["all_´_shift"],
    "all_´_capslock": ["all_´_shift"],       
    all_shift_capslock: ["all_shift"],
    all_capslock_shift: ["all_shift"],    
    all_shift_alt: ["all_alt_shift"],
    all_capslock_alt: ["all_alt_capslock"],
    all_alt_capslock_shift: ["all_alt_shift"],
    all_alt_shift_capslock: ["all_alt_shift"],
    all_shift_alt_capslock: ["all_alt_shift"],
    all_capslock_alt_shift: ["all_alt_shift"],
    all_capslock_shift_alt: ["all_alt_shift"],
    all_shift_capslock_alt: ["all_alt_shift"]
};
